---
- hosts: localhost
  tasks:
    - name: ensure required dirs
      file:
        dest: "{{ item }}"
        state: directory
      with_items:
        - external_libs
        - build
        - cache

    - name: ensure external libs
      git:
        repo: "{{ item.value }}"
        dest: "./external_libs/{{ item.key }}"
      with_dict:
        MFRC522: https://github.com/miguelbalboa/rfid
        ArduinoJson: https://github.com/bblanchon/ArduinoJson
