---
- hosts: all
  vars:
    control_machine_ssh_path: /Users/ko/.ssh/id_rsa.pub # @todo: move hardcoded variable outside
    remote_project_dir: /opt/chessbots
  tasks:
    # - debug: var=hostvars

    - name: update apt
      when: ansible_pkg_mgr == "apt"
      become: true
      apt: update_cache=yes

    - name: add authorized key of controll machine 
      authorized_key:
        user: pi
        key: "{{ lookup('file', control_machine_ssh_path) }}"

    - name: Add an Apt signing key, uses whichever key is at the URL
      when: ansible_pkg_mgr == "apt"
      become: true
      apt_key:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
        state: present

    - name: add yarn repo
      when: ansible_pkg_mgr == "apt"
      become: true
      apt_repository:
        repo: deb https://dl.yarnpkg.com/debian/ stable main
        state: present

    - name: update apt
      when: ansible_pkg_mgr == "apt"
      become: true
      apt: update_cache=yes

    - name: ensure additional packages
      become: true
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - nodejs
        - yarn

    - name: create tarball
      archive:
        path: ../javascript/*
        dest: ../proto.tgz
        exclude_path: ../javascript/node_modules
      delegate_to: localhost

    - name: ensure project dir exists
      become: true
      file:
        dest: "{{ remote_project_dir }}"
        state: directory
        owner: pi
        group: pi

    - name: extract chessbot code
      become: true
      unarchive:
        src: ../proto.tgz
        dest: "{{ remote_project_dir }}"
        owner: pi
        group: pi

    - name: yarn install
      shell: yarn install
      args:
        chdir: "{{ remote_project_dir }}"
