version: "3.9"

services:
  board:
    build: ./board
    volumes:
      - ./board:/app
    ports:
        - "8031:8031"
    working_dir: /app
    environment:
      FLASK_APP: flaskr
    command: 'flask run -p 8031 -h 0.0.0.0 --reload'
